### ISSUE TITLE
New errors for NOT_INCLUDED dwi sbref files

### ISSUE THREAD

**Issue by wangjinvandy** [bids-standard/legacy-validator#1145]
Hello, 

I have this following error but I checked the naming scheme of these data from bids specification webpage, they are all legal. This error message only occurred for our dwi data but not for func data. Does anyone have any clues of why? Thank you so much!

--- 

Error 2: [Code 1] NOT_INCLUDED
Click here for more information about this issue

Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.760 files
sub-5003_ses-7_acq-D2S10_sbref.json3.041 KB | application/json
Location:
bids/sub-5003/ses-7/dwi/sub-5003_ses-7_acq-D2S10_sbref.json

Reason:
Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.

Evidence:
sub-5003_ses-7_acq-D2S10_sbref.json

sub-5003_ses-7_acq-D2S10_sbref.nii.gz1425.021 KB | application/x-gzip
Location:
bids/sub-5003/ses-7/dwi/sub-5003_ses-7_acq-D2S10_sbref.nii.gz

Reason:
Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset (see https://github.com/bids-standard/bids-validator#bidsignore for details). Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.

Evidence:
sub-5003_ses-7_acq-D2S10_sbref.nii.gz

**Comment by wangjinvandy** [comment]
Hi, 
I did some digging, it looks like it should still be allowed given the code in lines 76-88 of the validator here https://github.com/bids-standard/bids-validator/blob/08a74cd85ea387cbb81291bbb5ad8c6987839997/bids-validator/bids_validator/rules/file_level_rules.json#L76-L88

 as you can see in line 80 that sbref is an accepted type. So it looks like there was a change made on Oct 9, 2020  https://github.com/bids-standard/bids-validator/commit/eaacb2cb20b9bd52ea0f45eab833fa4151a8ebea to line 77 and if you can see I think there shouldn’t be an underscore before @@@_dwi_type_@@@ which is the variable in line 80 that allows for sbref. It looks like they moved it from outside of a parentheses to inside which is still incorrect if comparing it to the functional line below which doesn’t have any underscore before @@@_func_ext_@@@ which I think is what allows it to call that variable in the regular expression. I am not super familiar with regular expressions though so I am not sure. 

Could anyone help with the correction with the code? Thank you!

**Comment by wangjinvandy** [comment]
According to the current bids specification, our naming convention should be fine. https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html

**Comment by sappelhoff** [comment]
Thanks for the additional info @wangjinvandy I tried to fix the issue in https://github.com/bids-standard/bids-validator/pull/1153 .. but we'll have to wait for maintainers who are more familiar with MRI to approve of that fix.

In the meantime, you could install a development version of the bids-validator and locally try out my changes from https://github.com/bids-standard/bids-validator/pull/1153

see more info here: https://github.com/bids-standard/bids-validator/blob/master/CONTRIBUTING.md#using-the-development-version-of-bids-validator

**Comment by wangjinvandy** [comment]
Hello, Thank you for your reply. Do you know when this change will be confirmed by the developer?

**Comment by sappelhoff** [comment]
I just merged #1153, so the fix is now available from the bids-validator `master` branch.

**Comment by wangjinvandy** [comment]
Hello, Thank you for the update. May I ask whether the bids-validator master branch is also used by the online validator and openNeuro webpage uploading step2? It appears that our dwi sbref.nii still cannot pass the validation using the online validator and OpenNeuro webpage. Looking forward to your reply. Thank you very much!

**Comment by sappelhoff** [comment]
Unfortunately the web and openneuro validators are using the latest release, not the development version (master) I advise you to download and use the command line interface version of the bids validator, see the readme file.

Else, you will unfortunately have to wait until the next release

**Comment by wangjinvandy** [comment]
Thank you very much for your quick reply. For uploading data to OpenNeuro, do we have to go through the steps of openneuro validators or we can change them by using your development version? If so, do you have an estimate of when the next release will happen? Looking forward to your reply as it will be important for us to make a final decision. Really appreciated it.

**Comment by effigies** [comment]
The next OpenNeuro update is likely to be in ~2 weeks. This fix can be included then. Are you able to install the validator locally to verify that your dataset will pass? If there are other issues that need to be resolved, it would be good to resolve them before then.

**Comment by wangjinvandy** [comment]
Yes, I tested your master version with python on our server. It works! Our dwi sbref.nii passed the validator. Please let us know when this fix will be applied to openneuro so we can start our data uploading to OpenNeuro. Thank you very much!
