### ISSUE TITLE
Python implementation incompatible with windows paths

### ISSUE THREAD

**Issue by MaxvandenBoom** [bids-standard/legacy-validator#959]
Hi guys,

I really like the cross-platform compatibility of the bids-validator and the .js node implementation works perfect, but the python implementation breaks on windows filepaths (due to the backslashed instead of forward slashes).

It is possible to change the slashes in the filepaths in my own code (before feeding them to python's is_bids function), however, that feels more like a workaround rather than a fixing the issue and keeping the bids-validator cross-platform.

There are two relatively easy fixes. One quick and dirty, which is to add: 
`path = path .replace("\\", "/")`
inside `is_bids`. But this might have an influence if you have backslashes in the directoryname (which is not allowed in windows, but is allowed on mac).

Or, a more elegant solution, is to adjust the test regexes to allow both a forward or a backward slash as directory seperator. e.g. to change: 
`"^\\/(sub-[a-zA-Z0-9]+)\\/\\1(@@@_subject_level_ext_@@@)$"`
to:
`"^(\\\\|\\/)(sub-[a-zA-Z0-9]+)\\/\\2(@@@_subject_level_ext_@@@)$"`
I guess this is more invasive since the regexes are used in general. Then again, it might also be a good thing to have the (general) regexes to be able to handle windows paths for the future.

What do you think? I am willing help and provide a PR, but I would like to know what you think first.

Regards,
Max

**Comment by MaxvandenBoom** [comment]
I am aware of issue https://github.com/bids-standard/bids-validator/issues/928, but I prefer not to settle for a workaround and am offering two solutions with a pull-request here

**Comment by sappelhoff** [comment]
Hi @MaxvandenBoom thanks for suggesting some improvements!

> But this might have an influence if you have backslashes in the directoryname (which is not allowed in windows, but is allowed on mac)

as far as I know this is also not allowed in BIDS :thinking: but I may fail to think about some edge case here.

potential third option:

Would it be an option to parse a regexp and replace any kind of slashes in the regexps with `os.sep` in Python?

Provided that these slashes are not escaped or escape slashes themselves?

Finally, I think it'd be good to first replicate the issue in our CIs before we start making fixes. I got started with that here: https://github.com/bids-standard/bids-validator/pull/933 but it currently only runs in the CircleCI workflow, which does not cover Windows.

If we agree that this issue should be solved (and I do agree) then perhaps a good first PR would be to add Windows testing of the Python bids-validator. 

I would vote for GitHub Actions, because they are easy to configure and offer to test on all 3 major OS see e.g.: https://github.com/sappelhoff/pyprep/blob/master/.github/workflows/python_tests.yml

WDYT @effigies @rwblair @nellh

**Comment by MaxvandenBoom** [comment]
Hi Stefan,

The regexes are the basis for checking paths in all interfaces. Replacing the slashes in python with `os.sep` is definitely also solution, but it still doesn't make the regexes os-compatible. So if you add another interface for a different language in the future, you would have to replace them in that situation as well to keep the whole OS-compatible. I think that adjusting the regexes is truly solving the source of the problem.

It sounds like a good idea to add Windows testing first! I guess you guys first need to decide and incorporate that in to your workflow, so for now I will just fork and adjust the regexes. Let me know if I can help out with anything regarding windows testing or another fix to this problem.

**Comment by sappelhoff** [comment]
@MaxvandenBoom did you implement your fix? Did you test it and does it work?

I think bids-validator would now be ready to receive a PR for fixing the windows functionality.

**Comment by MaxvandenBoom** [comment]
Hi Stefan! Yeah, I fixed the regexes and that works perfect!

I might have missed out on the latest progress a bit, so decision was to add windows testing on GitActions (https://github.com/bids-standard/bids-validator/pull/966), right?
Can I now just create a pull request with the updated regexes?

**Comment by sappelhoff** [comment]
> Hi Stefan! Yeah, I fixed the regexes and that works perfect!

nice

>  Can I now just create a pull request with the updated regexes?

yes please :)

**Comment by MaxvandenBoom** [comment]
All working now :)
